### ISSUE TITLE
Error with semantic-release

### ISSUE THREAD

**Issue by cpetta** [cpetta/sandpaper#36]
Documentating this error and it's fix:
original error:
```
error: gpg failed to sign the data

fatal: failed to write commit object

    at makeError (/home/travis/build/cpetta/sandpaper/node_modules/execa/index.js:174:9)

    at Promise.all.then.arr (/home/travis/build/cpetta/sandpaper/node_modules/execa/index.js:278:16)

    at process._tickCallback (internal/process/next_tick.js:68:7)

  code: 128,

  stdout: '',

  stderr:

   'error: gpg failed to sign the data\nfatal: failed to write commit object\n',

  failed: true,

  signal: null,

  cmd:

   'git commit -m chore(release): 1.0.1 [skip ci]\n\n## [1.0.1](https://github.com/cpetta/sandpaper/compare/v1.0.0...v1.0.1) (2019-10-16)\n\n\n### Bug Fixes\n\n* **clean:** callback must be a function ([4729b98](https://github.com/cpetta/sandpaper/commit/4729b982e88606bf0dcbd54d8359f693be12f20e))\n* **clean:** Callback must be a function ([055f88e](https://github.com/cpetta/sandpaper/commit/055f88ed7eccda6e669257e1cf66e23598a7c370))\n* **release:** add missing sem-rel changelog dependency ([c5259eb](https://github.com/cpetta/sandpaper/commit/c5259ebeaf217fec69d56a238ee1aba50edc81d9))\n* **release:** remove trailing comma ([e7413ea](https://github.com/cpetta/sandpaper/commit/e7413ea69e28b689ff2645f50a240fdb1a6ececb))\n\n\n\n',

  timedOut: false,

  killed: false,

  pluginName: '@semantic-release/git' }

Script failed with status #<struct Dpl::Provider::Status provider=Dpl::Providers::Script, status=:beta, info=nil>

failed to deploy
```

**Comment by cpetta** [comment]
Fixed by removing the 2 from /usr/bin/gpg2
```
- echo '/usr/bin/gpg2 --passphrase ${GPG_PASSPHRASE} --batch --no-tty "$@"' > /tmp/gpg-with-passphrase && chmod +x /tmp/gpg-with-passphrase
```
changed to:
```
- echo '/usr/bin/gpg --passphrase ${GPG_PASSPHRASE} --batch --no-tty "$@"' > /tmp/gpg-with-passphrase && chmod +x /tmp/gpg-with-passphrase
```

fixed for sandpaper with: e2bc7565fa1e6d7026352c5694164a1557b9811e
